### ISSUE TITLE
GitBook to Docusaurus - Migration Guide

### ISSUE THREAD

**Issue by app-generator** [app-generator/docs#10]
hello @kiptoo 

The migration from `GitBook` to `Docusaurus` should be fully documented in this document: (saved in the root of the project)

https://github.com/app-generator/docs/blob/main/README_Migrate_Gitbook.mdx

Ty!

**Comment by kiptoo** [comment]
in Progress

**Comment by app-generator** [comment]
Hello @kiptoo 

Any progress here? 
Ty!

**Comment by app-generator** [comment]
Validated. Closing.
