### ISSUE TITLE
UPD Django Section - Getting Started, Popular Modules

### ISSUE THREAD

**Issue by app-generator** [app-generator/docs#15]
Hello @BenFaruna 

The `Django` section needs to be updated with relevant data: 

- `technologies/django/getting-started.mdx`
- `technologies/django/popular-modules.mdx`
  - 10 great tools/libraries that every Django developer should know

Ty!

**Comment by BenFaruna** [comment]
Okay, I will get started on them

**Comment by app-generator** [comment]
Content Delivered:

> [Django Popular Modules](https://docs.appseed.us/technologies/django/popular-modules/)
