### ISSUE TITLE
Deployment AWS Django

### ISSUE THREAD

**Issue by app-generator** [app-generator/docs#20]
The documentation needs to be updated to cover this use case

- DOCS page: 
  - [docs/deployment/aws/django.mdx](https://github.com/app-generator/docs/blob/main/docs/deployment/aws/django.mdx)

**Comment by sgnd** [comment]
@app-generator This is done

**Comment by app-generator** [comment]
Validated. Ty @sgnd 

> [Deploy Django on AWS](https://docs.appseed.us/deployment/aws/django/)
