### ISSUE TITLE
Ubuntu - Getting Started 

### ISSUE THREAD

**Issue by app-generator** [app-generator/docs#34]
> Related DOCS  page: [Getting Started with Ubuntu](https://github.com/app-generator/docs/blob/main/docs/technologies/ubuntu/getting-started.mdx)

### Topics

- `Ubuntu` a short history
- `Ubuntu` How to install it 
  - Laptop (using a bootable image)
  - In a virtual machine via `VirtualBox` 
- How to manage the system using the CLI 
  - `sudo`
- Install the recommended packages for programming  
- How to add/remove users via CLI 
- How to install packages
- How to install MySql 
- How to install Python3  
- How to install Mysql 
- How to install PostgreSQL 
- How to install Redis 
- How to install Mongo 
- Services: how to create/suspend a service 
- CRON: create, list, and remove jobs

**Comment by sgnd** [comment]
Done

**Comment by app-generator** [comment]
Validated. Ty @sgnd 

> [Getting Started with Ubuntu](https://docs.appseed.us/technologies/ubuntu/getting-started/)
