### ISSUE TITLE
Flask Google OAuth - Material Kit Design 

### ISSUE THREAD

**Issue by app-generator** [app-generator/docs#45]
> Asked in support (Discord)

- DOCS page: [Flask Google OAuth](https://github.com/app-generator/docs/blob/main/docs/technologies/flask/oauth-google.mdx)
- Sample: https://github.com/app-generator/flask-google-oauth

Hello @BenFaruna! 

Please proceed with this task. Ty!

**Comment by app-generator** [comment]
Hello @BenFaruna 
any updates on this? 

TY!

**Comment by BenFaruna** [comment]
I'm almost done, I'll send it in by the end of the day or tomorrow tops
Sorry about the delay

**Comment by app-generator** [comment]
> Validated in tag `v1.0.35`
- [Flask Google OAuth](https://docs.appseed.us/technologies/flask/oauth-google/)

Ty @BenFaruna!
