### ISSUE TITLE
Dark Mode Switcher - icon not visible in white mode

### ISSUE THREAD

**Issue by app-generator** [app-generator/docs#5]
Hello @kiptoo 

The `dark mode` switcher Icon is not visible on WHITE Mode Active.

Please take a look. 

Ty!

![docs-dark-mode-icon-issue1](https://user-images.githubusercontent.com/51070104/208456114-47918688-b63e-4ffe-9772-3864c14cdf30.gif)

**Comment by kiptoo** [comment]
Bug fixed
