### ISSUE TITLE
Layout (HomePage) - Not mobile friendly 

### ISSUE THREAD

**Issue by app-generator** [app-generator/docs#7]
Hello @kiptoo, 

The homepage needs optimization for mobile.

Please take a look.

Ty! 

*** *** *** *** 
![image](https://user-images.githubusercontent.com/51070104/208457893-86e51ab1-d89c-4b4f-ac5f-be404640b7e3.png)

**Comment by kiptoo** [comment]
Responsiveness s now implemented
