### ISSUE TITLE
HOMEpage Mobile Issue 

### ISSUE THREAD

**Issue by app-generator** [app-generator/docs#8]
Hello @kiptoo 

On mobile, the HOMEpage has a strange, unoptimized layout. 

Please take a look. 
Ty! 

![docs-homepage-mobile-issue1](https://user-images.githubusercontent.com/51070104/212460310-3bcfbe48-6414-4559-a448-80e93ca4c5ff.gif)

**Comment by kiptoo** [comment]
Hi @app-generator ,
Sure lemme have a look and sort it out

**Comment by kiptoo** [comment]
sorted kindly pull and do npm i before building

**Comment by app-generator** [comment]
Validated. Closing.
